#!/bin/bash

SNIF_DIR=`dirname $0`

mkdir -m 02775 $SNIF_DIR/crt
mkdir -m 02775 $SNIF_DIR/csr
mkdir -m 02775 $SNIF_DIR/cfg
mkdir -m 02775 $SNIF_DIR/arc
mkdir -m 02775 $SNIF_DIR/var
mkdir -m 02775 $SNIF_DIR/apns

mkfifo -m 0620 $SNIF_DIR/var/snif-certd.ctl
mkfifo -m 0640 $SNIF_DIR/var/snifd-in.ctl
mkfifo -m 0620 $SNIF_DIR/var/snif-apnsd.ctl
