#!/bin/bash

#/**************************************************************************
# *     _________
# *    /````````_\                  S N I F ~ e2e TLS trust for IoT
# *   /\     , / O\      ___
# *  | |     | \__|_____/  o\       e2e TLS SNI Forwarder
# *  | |     |  ``/`````\___/       e2e TLS CA Proxy
# *  | |     | . | <"""""""~~
# *  |  \___/ ``  \________/        https://snif.host
# *   \  '''  ``` /````````         (C) 2021-2026 VESvault Corp
# *    \_________/                  Jim Zubov <jz@vesvault.com>
# *
# *
# * Apache License, Version 2.0
# * You may use, copy, modify, merge, publish, distribute and/or sell copies
# * of the Software under the terms of the Apache License, Version 2.0, a copy
# * of which is provided in the COPYING file, or http://www.apache.org/licenses/LICENSE-2.0
# *
# * This software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# * CONDITIONS OF ANY KIND, either express or implied.
# *
# **************************************************************************/

# Create the runtime directories and control pipes the SNIF CA proxy daemons
# and scripts expect. Resolve the base dir from /etc/snif.conf (the same
# SNIF_CA_PROXY the daemons read); fall back to this script's own directory.

[ -r /etc/snif.conf ] && . /etc/snif.conf
SNIF_DIR="${SNIF_CA_PROXY:-$(dirname "$0")}"

mkdir -m 02775 "$SNIF_DIR/crt"
mkdir -m 02775 "$SNIF_DIR/csr"
mkdir -m 02775 "$SNIF_DIR/cfg"
mkdir -m 02775 "$SNIF_DIR/auth"
mkdir -m 02755 "$SNIF_DIR/arc"
mkdir -m 02755 "$SNIF_DIR/var"
mkdir -m 02775 "$SNIF_DIR/apns"
mkdir -m 02775 "$SNIF_DIR/log"

mkfifo -m 0620 "$SNIF_DIR/var/snif-certd.ctl"
mkfifo -m 0620 "$SNIF_DIR/var/snifd-in.ctl"
mkfifo -m 0640 "$SNIF_DIR/var/snifd-out-apnsd.ctl"
